# Generated by Django 5.2.6 on 2025-09-25 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="category",
            field=models.CharField(
                choices=[
                    ("cooked_meal", "Cooked Meal"),
                    ("bakery_goods", "Bakery Goods"),
                    ("produce", "Fruits & Vegetables"),
                    ("packaged_items", "Packaged & Canned Goods"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="pickup_by",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The food must be picked up before this date and time.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                default="9801237680",
                help_text="Enter your 10-digit phone number.",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
