# Generated by Django 5.2.6 on 2025-10-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_donation_category_donation_pickup_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="donation",
            name="category",
            field=models.CharField(
                choices=[
                    ("veg", "Cooked Meal (Veg)"),
                    ("non_veg", "Cooked Meal (Non-Veg)"),
                    ("packaged", "Packaged Food"),
                    ("fruits_veg", "Fruits & Vegetables"),
                    ("bakery", "Bakery Items"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="food_item",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="donation",
            name="pickup_by",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="donation",
            name="quantity",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("claimed", "Claimed"),
                    ("completed", "Completed"),
                ],
                default="available",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
